### ISSUE TITLE
this is test

### ISSUE THREAD

**Issue by hankeke** [hankeke/log4js#48]
this is test near

**Comment by BytePay-sealos** [comment]
**Bytepay: Finish This Task, hankeke will pay you 0.01 NEAR.**

  
Comment in Following instruction to apply for this task

  
`/bytepay apply`

  
Visit http://localhost:10086 for more detail

**Comment by BytePay-sealos** [comment]
**Bytepay: Task has been assigned to @laf-yun.**

**Comment by BytePay-sealos** [comment]
**@laf-yun:**

  
**hankeke have paid for this task**, visit https://explorer.near.org/transactions/5fuZeRD6BeBcuNWiZjen5VzS2TmYiNdpEYLymSsWbKQL  for detail
